---
title: "Idées de projets"
author: "Visseho Adjiwanou, PhD."
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document: default
  html_document: default
---

## Introduction

Il est possible que vous n'ayiez pad d'idées sur ce que vous aimeriez faire. Il n'est pas important que vous travailliez forcément sur vos projets, d'ailleurs, ce n'est pas toujours une bonne idée (car cela peut vous donner l'illusion que vous avez déjà tout fait). Par contre, en travaillant sur d'autres projets, vous pouvez acquérir une compétence complémentaire (autres méthodes) et avoir la possibilité de publier plus d'un article avant la fin de votre maîtrise. C'est une bonne opportunité pour des demandes de subventions pour votre thèse. Bien évidemment, si vous travaillez en plus sur vos propres données, je serai ravi d'en discuter avec vous et de vous lire. Si à la fin, ce projet devient votre Je vous présente ici quelques idées qui peuvent vous intéresser:

# 1. Famille

La transition familiale en cours dans l'ensemble des pays du monde nécessite des études pour mieux comprendre les facteurs en cause et les conséquences de ces changements familiaux sur les enfants et les femmes.

Quelques questions de recherches intéressantes:


## 1.1. Artcles concernant les pays développés et bases de données

### 1.1.1 Articles 

Bignami-Van Assche, S., & Adjiwanou, V. (2010). Dynamiques familiales et activité sexuelle précoce au Canada. Cahiers Québécois de Démographie, 38(1), 41–69. https://doi.org/10.7202/039988ar

  - Base de données: 


### 1.1.2. Base de données


## 1.2 Articles concernant les pays en développement et bases de données

### 1.2.1.Article

Adjiwanou, V. (2017). Step family in sub-Saharan Africa: Trends and consequences on child and adolescent well-being. Population Association of America, Chicago, USA, April 27-April, 29.

# 2. Santé






