---
title: "Travail de fin de session"
author: "Visseho Adjiwanou, PhD."
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document: default
  html_document: default
---


# Travail de session

## 1. Introduction

L'examen final est la rédaction d'un article original ou la réplication d'un article de votre choix ou choisi par le professeur. Ce travail doit être produit à l'aide d'un fichier Rmd. et le fichier pdf doivent être soumis. Chaque projet doit aller au delà de la simple analyse descriptive: vous devez utiliser au moins d'une des méthodes vues en classes. Un bon projet est celui qui combine les approches traditionnelles avec les approches issues des données digitales. Il serait ainsi intéressant si vous pouvez utiliser les données secondaires avec des données que vous collecter vous-même sur les plateformes digitales. 

Ce projet doit être sérieux et vous permettre de pouvoir le continuer plus tard pour publication. Vous devez accorder une grande importance à la qualité du texte, aux tableaux et graphiques. Voici un exemple d'articles pour vous: https://www.erudit.org/en/journals/crs/2017-n63-crs04254/1055723ar/. Votre article doit être plus court. Votre recension des écrits doit être plus courte: juste vous intéresser à la théorie et à deux ou trois articles empiriques. Votre méthodologie doit être claire: vous devez clairement justifier le choix de votre échantillon.


## 2. Que doit contenir ce document

Dans l'un ou l'autre cas, voici ce que ce document doit comprendre:

1. Une **introduction** succincte et claire. Cette introduction doit comporter plus ou moins 4 paragraphes avec les éléments suivants:
  - Paragraphe 1: Quel est le sujet à l’étude et pourquoi est-il important?
  - Paragraphe 2: Que savons-nous sur le sujet?
  - Paragraphe 3: Quelles sont les limites des précédentes études?
  - Paragraphe 4: Qu'est-ce que je veux faire et comment je veux le faire? C'est ici que vous présentez vos questions de recherche **ou** vos objectifs général et spécifiques. De même, vous présentez brièvement vos données et l'approche méthodologique.

2. Une **revue théorique** relevant la/les théorie(s) sociologique(s) sur laquelle vous basez votre recherche et une **revue empirique** mettant **surtout** l'accent sur les problèmes méthodologiques des anciennes études. 

3. Une **méthodologie** présentant les données et votre approche méthodologique

4. La présentation des résultats

5. La discussion des résultats, la présentation des limites de l'étude et les recherches prospectives.

6. Références bibliographiques

Ce document doit être de 7500 mots (enciron 15 pages, sans les annexes). 

## 3. Échéance et notation

1. Présentation préliminaire de votre projet (partie 1 à 3) : 1 novembre (15%)
2. Deuxième présentation de de votre projet (Partie 3 et 4) : 13 décembre (20% de la note finale)
3. Travail final soumis (65%)
  - 70% sur le fond
  - 10% sur la forme. Prêtez attention à l'écriture et à la qualité du document.

Le calendrier est suggestif. 

## 4. Autres éléments à considérer

- **Langage de soumission** : français ou anglais

- **Taille du manuscrit** : 4500 mots. Environ 15 pages. La dimension maximum du manuscrit comprend les espaces, les annexes, les références, le résumé (160 à 200 mots), les mots-clés (5 à 8), les tableaux, les figures. Chaque tableau, figure et carte doit comporter titre, légendes et source.

- **Nombre de tableaux**: ce document doit comporter au moins 3 tableaux, un tableau descriptif, un tableau croisé entre les variables dépendantes et la variable dépendante, et les tableaux explicatives.

- **Nombre de graphiques**: Vous devez présenter au moins 3 graphiques, un graphique pour présenter la variable dépendante, et d'autres graphiques.

- **Formules mathématiques** : Elles sont numérotées à droite, appelées dans le texte et présentées de façon lisible.

- **Notes de bas de page** : Les notes de bas de page sont numérotées séquentiellement et ne comportent ni tableau, ni graphique.

- **Références bibliographiques** : Elles sont disposées en fin d’article, par ordre alphabétique d’auteurs, pour chaque auteur dans l’ordre chronologique, et appelées dans le texte sous la forme (Laslett, 1977) ou (Ekert-Jaffé et al., 2002 ; Delbès et Gaymu, 2005). 
Ceci peut se faire directement dans RMarkdown: https://christopherjunk.netlify.com/blog/2019/02/25/zotero-rmarkdown/

  - *Présentation pour un article de revue* : D’ALBIS H., BOUBTANE E., 2015, « Caractérisation des flux migratoires en France à partir des statistiques de délivrance de titres de séjour (1998-2013) », Population 70(3), p. 487-523.

  - *Pour un ouvrage* : KAPKO Nathalie, 2007, L’islam, un recours pour les jeunes, Paris, Presses de la fondation nationale des sciences politiques, 197 p.

  - *Pour un chapitre d’ouvrage* : LEVY Marie-Françoise, 2008, « Les femmes du temps présent à la télévision : la mutation des identités (1960-1975) », in Dreyfus-Armand Geneviève, Frank Robert, Levy Marie-Françoise et al. (dir.), Les années 68. Le temps de la contestation, Paris, Complexe, p. 199-216.
  
## 5. Compétences acquises

A part une compétence certaine que vous allez acquérir dans l'écriture d'un article scientifique, vous allez maîtriser un logiciel de référence bibliographique (Zotéro) et son intégration dans RMarkdown. Tout le travail doit se faire avec RMarkdown avec la production de l'article dans un format pdf ou Word.